### ISSUE TITLE
Featured Products section cannot be disabled

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/boutique#37]
Ticket: 562894-zd-woothemes

When using Homepage Control, all sections can be deactivated except the "Featured Products" section. For a better illustration, have a look at the following screenshot:

![http://cld.wthms.co/K79T](http://cld.wthms.co/K79T+)
Full Image: http://cld.wthms.co/K79T+

Local testing site is using:

* Storefront 2.1.8
* Boutique 2.0.7
* Homepage Control 2.0.0

**Comment by jameskoster** [comment]
This isn't a bug. The featured products aren't hooked into the `homepage` action so Homepage Control won't detect them. See https://github.com/woocommerce/boutique/blob/master/inc/class-boutique-template.php#L29

This was done to mirror the 'Wootique' theme that this child theme was designed to replace. Luckily it's a very simple snippet to remove it if folks want to. Or of course they could just not set any featured products.
