### ISSUE TITLE
Stripe payment box background is being set to 

### ISSUE THREAD

**Issue by Trebacz** [woocommerce/boutique#38]
The Stripe credit card payment form (#wc-stripe-cc-form) is being set to a gray (background-color: #a9a9a9) background color. For the life of me I can't figure where it's coming from. Disabling any other plugin that references that color in code doesn't change it (eliminated plugin conflicts).

Switching to base storefront template also eliminates the gray form background. I assume this is somehow being set in customizer, but I think it's a bug, so I'm reporting it here.

Not sure when it appeared -or if I have always missed it.

![grey box in stripe payment](https://user-images.githubusercontent.com/19363347/26847413-d5ae1252-4ab1-11e7-9c6b-2883a0041fbb.png)
Here is the URL to the production site: https://www.glasshousestore.com

**Comment by tiagonoronha** [comment]
This is the CSS causing the issue:

``table tbody tr:nth-child(2n) td,fieldset,fieldset legend{background-color:#a9a9a9}``

I don't see any CSS styling in Boutique that styles the background color of `fieldset` elements.

Either way, adding the following custom CSS should fix the issue for you:

`fieldset {
    background-color: transparent;
}`

**Comment by Trebacz** [comment]
Thanks. I went with the following CSS override to be a bit more specific:
`fieldset#wc-stripe-cc-form { background-color: transparent; }`
It's interesting that StoreFront without Boutique as a child theme it's okay. Not sure what the difference is, but appreciate you taking a look at it...

**Comment by Ruben2600** [comment]
93/5000
Hello, can anyone help me with this? The above codes don't work for me!


Thanks :)
