### ISSUE TITLE
Deactivated WooCommerce causes extra header margin

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/boutique#39]
Ticket: 723759-zd-woocommerce

When WooCommerce is deactivated, there is an extra margin below the header. Compare the following:

**WooCommerce Deactivated**

![http://cld.wthms.co/3U4Xi6](http://cld.wthms.co/3U4Xi6+)
Full Image: http://cld.wthms.co/3U4Xi6+

**WooCommerce Activated**

![http://cld.wthms.co/CTSGQk](http://cld.wthms.co/CTSGQk+)
Full Image: http://cld.wthms.co/CTSGQk+

**Comment by GlennMartin1** [comment]
an almost identical issue exists in Deli, as well.

**Comment by RiaanKnoetze** [comment]
Temporary workaround is to add the following custom CSS under **Appearance > Customize > Additional CSS**:

```
body.no-wc-breadcrumb .site-header {
    margin: 0;
}
```
