### ISSUE TITLE
Background color does not change with customizer

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/boutique#40]
Using Background color option under **Appearance > Customize** the color reverts to grey when choosing white ( ffffff ) as a color. Any other color works as expected.

![prtwg2](https://user-images.githubusercontent.com/2876178/32517009-c512d440-c3ca-11e7-95e0-583981784067.gif)

**Comment by GlennMartin1** [comment]
This issue affects other themes as well, specifically in Homestore. But there's no public Git for Homestore. I think it's also on Toy Store and Deli, as I recall. 

It also affects not only Background Colour, but other header attribute as well. Try font color, etc...

**Comment by dougaitken** [comment]
@tiagonoronha We've had this ticket on-hold, wondering if you have any ideas about this one, and the same for Deli? Thanks!
