### ISSUE TITLE
Boutique doesn't respect PowerPack designer settings....

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/boutique#44]
WordPress 4.9.1
Storefront 2.2.5
Boutique 2.0.11
Powerpack 1.4.4

Have no logo file set.

Then:
Go to: **Customize > Powerpack > Header > Customize Header**
Click **Logo**. This will put the site title in the header.

Then:
Go to **Customize > Powerpack > Designer > Add a style**
Click on the site title in the header to customize it.

Change some settings. Many of them don't work.
- Font doesn't work.
- Text color doesn't work.
- Bold doesn't work.
- Line height doesn't work.
- Letter spacing doesn't work.

This is just an example, but it's not limited to the site title.

**Comment by GlennMartin1** [comment]
Same issues exist in Deli
https://github.com/woocommerce/deli/issues/28

**Comment by tiagonoronha** [comment]
Hi! This is an issue in Powerpack, not Boutique or Deli.

Please contact us via our support channels. Thanks!
