### ISSUE TITLE
how to set image sizes in boutique with new woo 3.3.1

### ISSUE THREAD

**Issue by yatgirl** [woocommerce/boutique#45]
I have updated my staging site only so far to woo 3.3.1, I am using storefront with a boutique child theme. Under customizing – woocommerce – product images – there is no option to set the sizein the customizer My thumbnails are now 171 x 171 and I need them to be 150 x 150 for my layout. Can you please advise how I now change the thumbnail settings for boutique ?

Prior I set the thumbnail size in wordpress media settings to 150 x 150 and also in woocommerce settings products display to 150 x 150 and it worked for my layout.

Can you please help me out by advising where I can get help on this or how I can do this now ?

**Comment by tiagonoronha** [comment]
@yatgirl is there a particular reason why you need the image to be smaller? Image should adapt to the available space.

Do you have a link to the site in question?

**Comment by yatgirl** [comment]
Yes, that is the way I designed my store prior to Woo 3.3.1 and the latest Boutique update and the larger images didnt look good with my layout as I have 4 columns instead of the Boutiques standard 3 columns.  I have solved the issue by using additional css under Customizing.  
https://dogshoppe.net
Thanks !
