### ISSUE TITLE
Changelog Not Updated

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/boutique#46]
The changelog currently reflects version 2.0.11 when 2.0.12 is the latest version:

https://demo.woothemes.com/wp-content/themes/boutique/changelog.txt

**Comment by tiagonoronha** [comment]
The demo hasn't been updated to the latest version yet.

**Comment by zwiesman31** [comment]
Is there a reason why the product page links to the demo changelog: 

![http://cld.wthms.co/bN5xog](http://cld.wthms.co/bN5xog+)

Shouldn't the marketing page show the updated changelog? 

I can post this on the .com repo if you think it's more appropriate for there @tiagonoronha? Thanks!

**Comment by tiagonoronha** [comment]
Since Boutique and the other free child themes are hosted on WordPress.org, they are considered "external" products. That's why we use the demo changelog there.

I'll update the demos today.
