### ISSUE TITLE
Add to Cart button is missing and price styling is off for Featured Products

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/boutique#57]
#### Affected tickets 

1280920-zen

#### What I expected

To add some products in the Featured section on the homepage

#### What happened instead

These products don't have an Add to Cart button. Also, product prices are aligned to bottom-right and displayed in two lines:

![Screenshot](http://cld.wthms.co/D6SOSw+)
Screenshot: http://cld.wthms.co/D6SOSw

Other homepage sections have the price displayed in one line and aligned to top right:

![Screenshot](http://cld.wthms.co/nSdvGG+)
Screenshot: http://cld.wthms.co/nSdvGG

#### Steps to reproduce

1. Create a homepage from the Storefront homepage template
2. Flag some products as featured
3. Open the homepage and observe

Reproduced with SF 2.3.2 & Boutique 1.0.14

**Comment by tiagonoronha** [comment]
@madeincosmos PR here: https://github.com/woocommerce/boutique/pull/58

Just a quick comment to let you know that the "Add to cart" button is not supposed to show up in the Featured Product section.
