### ISSUE TITLE
Missing Homepage Content section when using Homepage Control

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/boutique#59]
When using Boutique with Homepage Control, the **Homepage Content** section is not an option to move/deactivate.

Here's a screenshot to illustrate that better:

![http://cld.wthms.co/U18lfE](http://cld.wthms.co/U18lfE+)
Full Image: http://cld.wthms.co/U18lfE+

It is, however, possible with Powerpack:

![http://cld.wthms.co/9zKe4T](http://cld.wthms.co/9zKe4T+)
Full Image: http://cld.wthms.co/9zKe4T+

**Comment by tiagonoronha** [comment]
In Boutique, the homepage content and also the featured products were moved to a different action `boutique_before_homepage_content`.

For that reason, Homepage Control is not able to pick up this sections.

Please recommend removing via an action, or Powerpack.

`remove_action( 'boutique_before_homepage_content', 'storefront_homepage_content', 10 );`

and

`remove_action( 'boutique_before_homepage_content', 'storefront_featured_products',	20 );`
