### ISSUE TITLE
Unable to view cart icon on mobile version of site

### ISSUE THREAD

**Issue by m155y** [woocommerce/boutique#66]
_Boutique Version: 2.0.17_
2951387-zen

**Steps to Reproduce**

- Install Boutique Child Theme
- View store on a mobile browser
- Add product to the cart
- Observe that cart icon is no longer visible on mobile version, so customer is unable to go to their cart

I was able to recreate this on my test site:

![Screen Capture on 2020-05-06 at 16-20-24](https://user-images.githubusercontent.com/49052939/81225777-caa7c080-8fb7-11ea-84ab-57e9f7f234a5.gif)

**Comment by nielslange** [comment]
Hello @m155y 👋 The grid point of the Boutique theme is 768px. If the screen has a width of 768px or more, the desktop version is visible, which shows the cart icon in the upper-right corner:

![#66-desktop](https://user-images.githubusercontent.com/3323310/81286710-b1704400-908b-11ea-8eb1-a53b83392a57.png)

If the screen width is smaller than 768px, the cart icon shows in the footer bar on the right-hand side:

![#66-mobile](https://user-images.githubusercontent.com/3323310/81286717-b33a0780-908b-11ea-950a-d9db15ac92ff.png)

Based on the chat and the notes, it's not obvious to me what the customer's URL is. In case http://ratsastuskauppa.fi/ is their site, they seem to have changed the theme already. Also, on your screenshot, I can only see the desktop view with the cart icon, but not the mobile view.

The screenshots, I added above, are created on my local environment, but on the demo page of the Boutique theme on https://themes.woocommerce.com/boutique/ the cart icons are also visible for both the mobile and the desktop view. Can you confirm that you're seeing the same results as I, after my explanation?

**Comment by m155y** [comment]
Hi @nielslange -

Oh for the love of pete. I am so sorry. I didn't see that at the bottom of the mobile version!! YES it's there. And what's super confusing is the customer had the same theme that's on their site now (http://ratsastuskauppa.fi), so I'm not seeing it there either. Their SSR showed they were using the Boutique theme, which upon further inspecting their html, they are NOT using. They are using a 3PD theme (Flatsom) and I didn't catch that it mismatched their SSR.

So, nothing to see here. You can close this out. :) Thank you!

**Comment by nielslange** [comment]
Hello @m155y  👋 I'm glad this issue is solved and I'll close it for now. And please don't worry about reporting this issue. It's better to report and issue that isn't one than to not report an actual issue. 😉
