### ISSUE TITLE
Update contributor

### ISSUE THREAD

**Issue by jconroy** [woocommerce/boutique#68]
Update contributors to include `woocommerce,automattic,`

woothemes can stay etc.

**Comment by luislard** [comment]
@jconroy this already has a PR maybe we need to move it to in progress

**Comment by nielslange** [comment]
> @jconroy this already has a PR maybe we need to move it to in progress

@luislard That was my bad. I wasn't aware that this issue was on your list and while doing some housekeeping, I just created a PR to get this issue fixed. I just moved the card to _"In Progress"_. Sorry for the confusion.
